bl2_plat_setup: mp2: remove boardinfo from log
'board_id' has been removed from 'bsec' since the BOARD_ID OTP is a
custom STM implementation, producing the following message in the TF-A
boot console:

    ERROR:   nvmem node board_id not found

Remove the boardinfo log to avoid seeing this message.

Signed-off-by: Gonzalo Ruiz <Gonzalo.Ruiz@digi.com>